Repository amosproj/amos2024ss06-health-ai-framework, pull requests merged in 2024-05, with the labels that each got.

#45 Added scraper for All recipe.com
  src/backend/data_acquisition/scrapers/Allrecipes.com/allrecipes.py
  src/backend/data_acquisition/scrapers/Allrecipes.com/main.py
Labels: sprint-03, release: feature

#33 GitHub actions to check code style and linting
  .github/workflows/check_codestyle.yml
  .github/workflows/draft_helper.yml
  .github/workflows/review_request.yml
Labels: release: feature

#46 Submit amos documents for sprint 03
  Deliverables/sprint-03/Dummy.md
  Deliverables/sprint-03/feature-board.png
  Deliverables/sprint-03/feature-board.tsv
  Deliverables/sprint-03/imp-squared-backlog.png
  Deliverables/sprint-03/imp-squared-backlog.tsv
  Deliverables/sprint-03/planning-document.pdf
Labels: release: sprint-deliverables

#47 Directory naming convention & code style
  src/backend/data_acquisition/scrapers/Allrecipes.com/allrecipes.py
  src/backend/data_acquisition/scrapers/Allrecipes.com/main.py
  src/backend/data_acquisition/scrapers/all_recipes/allrecipes.py
  src/backend/data_acquisition/scrapers/all_recipes/main.py
Labels: release: bug-fix

#51 fixed pubmed merge errors and pdm lock errors
  pdm.lock
  src/backend/data_acquisition/scrapers/pubmed/pubmed_scraping.py
Labels: release: bug-fix

#57 fix: orchestrator import error
  src/backend/data_acquisition/orchestrator.py
Labels: release: bug-fix

#59 Fix utf encoding error
  src/backend/data_acquisition/scrapers/pubmed/pubmed_scraping.py
Labels: bug, release: bug-fix

#64 GitHub CI CD fixes
  .github/workflows/check_codestyle.yml
  .github/workflows/draft_helper.yml
  .github/workflows/review_request.yml
Labels: release: bug-fix

#68 Auto write release note
  .github/release-drafter.yml
  .github/workflows/draft_helper.yml
Labels: release: feature

#63 Arxiv scraping is done
  pdm.lock
  pyproject.toml
  src/backend/data_acquisition/config.json
  src/backend/data_acquisition/config.py
  src/backend/data_acquisition/scrapers/arxiv/arxiv_scraping.py
  src/backend/data_acquisition/scrapers/pubmed/pubmed_scraping.py
  src/backend/data_acquisition/scraping_data_element.py
Labels: release: feature

#79 Enhance arxiv scraper to include the new orchestrator methods
  pyproject.toml
  src/backend/Config/main.py
  src/backend/Scrapers/Archive/__init__.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/Archive/main.py
  src/backend/ScrappingTarget/archive_target.py
Labels: release: refactor

#78 Allrecipes scrapping pipeline as per new orchestrator implementation
  src/backend/Scrapers/AllRecipes/__init__.py
  src/backend/Scrapers/AllRecipes/all_recipes.py
Labels: sprint-04, domain: data pipeline, release: feature

#80 Apptainer build process to run app within HPC
  .gitignore
  Apptainer.def
  Documentation/hpc_setup.md
Labels: release: bug-fix

#65 Podcast scraper fixes (code cleaning & deleting audio raw files)
  src/backend/Scrapers/PodCast/podcast_scraping_old.py
Labels: release: bug-fix

#77 Nutritionfacts scraping
  pdm.lock
  pyproject.toml
  src/backend/Scrapers/Nutritionfacts/main.py
  src/backend/Scrapers/Nutritionfacts/nutritionfacts.py
Labels: feature, release: feature

#85 Fixed sentence_transformers dependency
  pdm.lock
  pyproject.toml
Labels: release: bug-fix

#102 Submit amos documents for sprint 04
  Deliverables/sprint-04/dummy.md
  Deliverables/sprint-04/feature-board.png
  Deliverables/sprint-04/feature-board.tsv
  Deliverables/sprint-04/imp-squared-backlog.png
  Deliverables/sprint-04/imp-squared-backlog.tsv
  Deliverables/sprint-04/planning-document.pdf
Labels: release: sprint-deliverables

#104 GitHub CI-CD checkout version bump to 4
  .github/issue-branch.yml
  .github/release-drafter.yml
  .github/workflows/check_codestyle.yml
  .github/workflows/create_link_issue_branch.yml
  .github/workflows/draft_helper.yml
  .github/workflows/review_request.yml
Labels: release: bug-fix

#105 Podcast scrapper refactored (orchestrator)
  pyproject.toml
  src/backend/Config/main.py
  src/backend/Scrapers/AllRecipes/__init__.py
  src/backend/Scrapers/Archive/__init__.py
  src/backend/Scrapers/PodCast/__init__.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PodCast/podcast_scraping_old.py
  src/backend/Scrapers/PubMed/__init__.py
  src/backend/ScrappingTarget/podcast_target.py
Labels: release: refactor

#108 Auto .env creation when .env.template change
  .env.template
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/__init__.py
Labels: release: feature

#109 Error Handling while scrapping and Save method updated to `json` format
  src/backend/Config/main.py
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/PodCast/pod_cast.py
Labels: release: bug-fix

#111 Added new `run` method to scrape one target
  src/backend/Orchestrator/orchestrator.py
Labels: release: feature

#114 Wireframes for frontend
  Documentation/Frontend Wireframe.pdf
Labels: release: feature

#116 Update README.md
  README.md
Labels: sprint-05, release: sprint-deliverables, domain: po

#120 Add documents for sprint 05
  Deliverables/sprint-05/feature-board.png
  Deliverables/sprint-05/feature-board.tsv
  Deliverables/sprint-05/imp-squared-backlog.png
  Deliverables/sprint-05/imp-squared-backlog.tsv
  Deliverables/sprint-05/planning-document.pdf
Labels: sprint-05, release: sprint-deliverables

#121 Change: Tab size to 4 and line size to 100 chars
  ruff.toml
  src/backend/RAG/LangChain_Implementation/basic_retrieval.py
  src/backend/RAG/create_embeddings/create_embeddings.py
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/Nutritionfacts/nutritionfacts.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/__init__.py
Labels: release: bug-fix
