Repository amosproj/amos2024ss06-health-ai-framework, pull requests merged in 2024-06, with the labels that each got.

#145 88 Integrate Pubmed Scraper into Data Pipeline
  src/backend/Config/__init__.py
  src/backend/Config/config.py
  src/backend/Config/main.py
  src/backend/Orchestrator/main.py
  src/backend/Orchestrator/orchestrator.py
  src/backend/Scrapers/AllRecipes/__init__.py
  src/backend/Scrapers/AllRecipes/main.py
  src/backend/Scrapers/Archive/__init__.py
  src/backend/Scrapers/Archive/main.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/main.py
  src/backend/Scrapers/PodCast/__init__.py
  src/backend/Scrapers/PodCast/main.py
  src/backend/Scrapers/PubMed/__init__.py
  src/backend/Scrapers/PubMed/main.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/__init__.py
  src/backend/Scrapers/YouTube/main.py
  src/backend/ScrappingTarget/all_recipes_target.py
  src/backend/ScrappingTarget/archive_target.py
  src/backend/ScrappingTarget/base_target.py
  src/backend/ScrappingTarget/podcast_target.py
  src/backend/ScrappingTarget/pubmed_target.py
  src/backend/ScrappingTarget/youtube_target.py
Labels: release: feature

#146 126 patch for the pubmed scraper pdf downloading problems
  src/backend/Config/main.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/PubMed/main.py
  src/backend/Scrapers/PubMed/pub_med.py
Labels: release: bug-fix

#150 Create Wiki-documentation
  Deliverables/sprint-06/build-documentation.pdf
  Deliverables/sprint-06/design-documentation.pdf
  Deliverables/sprint-06/user-documentation.pdf
Labels: release: sprint-deliverables

#151 NutritionFacts orchestrator functionality
  pdm.lock
  pyproject.toml
  src/backend/Config/config.py
  src/backend/Config/main.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/Nutritionfacts/__init__.py
  src/backend/Scrapers/Nutritionfacts/main.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/Nutritionfacts/nutritionfacts.py
  src/backend/ScrappingTarget/nutrition_target.py
Labels: release: refactor

#158 complete the wireframe task to include the document download functionality #125
  Documentation/Frontend Wireframe .pdf
  Documentation/Frontend Wireframe.pdf
Labels: app frontend, release: bug-fix

#148 Dependencies Clean-Up
  chroma_db/chroma.sqlite3
  chroma_db/e9815e86-9ce1-4d9f-ae15-16e528acbbd1/header.bin
  chroma_db/e9815e86-9ce1-4d9f-ae15-16e528acbbd1/length.bin
  chroma_db/e9815e86-9ce1-4d9f-ae15-16e528acbbd1/link_lists.bin
  pdm.lock
  pyproject.toml
  ruff.toml
  src/backend/Config/config.py
  src/backend/Config/main.py
  src/backend/Orchestrator/orchestrator.py
  src/backend/RAG/LangChain_Implementation/basic_retrieval.py
  src/backend/RAG/LangChain_Implementation/blog_data.json
  src/backend/RAG/create_embeddings/create_embeddings.py
  src/backend/RAG/create_embeddings/env
  src/backend/Scrapers/AllRecipes/__init__.py
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/AllRecipes/main.py
  src/backend/Scrapers/Archive/__init__.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/Archive/main.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/__init__.py
  src/backend/Scrapers/Nutritionfacts/main.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/PodCast/__init__.py
  src/backend/Scrapers/PodCast/main.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PubMed/__init__.py
  src/backend/Scrapers/PubMed/main.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/__init__.py
  src/backend/Scrapers/YouTube/main.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/ScrappingTarget/all_recipes_target.py
  src/backend/ScrappingTarget/podcast_target.py
  src/backend/Types/__init__.py
  src/backend/Types/all_recipes.py
  src/backend/Types/archive.py
  src/backend/Types/base_type.py
  src/backend/Types/nutrition.py
  src/backend/Types/pod_cast.py
  src/backend/Types/pub_med.py
  src/backend/Types/you_tube.py
  src/backend/__init__.py
Labels: release: refactor

#157 React Native mobile App set-up
  .gitignore
  app.json
  assets/adaptive-icon.png
  assets/favicon.png
  assets/fonts/OpenSans-Bold.ttf
  assets/fonts/OpenSans-ExtraBold.ttf
  assets/fonts/OpenSans-Light.ttf
  assets/fonts/OpenSans-Medium.ttf
  assets/fonts/OpenSans-Regular.ttf
  assets/fonts/OpenSans-SemiBold.ttf
  assets/icon.png
  assets/splash.png
  babel.config.js
  biome.json
  eas.json
  package.json
  src/frontend/App.tsx
  src/frontend/components/UpdateApp/index.tsx
  src/frontend/components/index.ts
  src/frontend/helpers/fonts.ts
  src/frontend/helpers/index.ts
  src/frontend/helpers/themes.ts
  src/frontend/hooks/index.ts
  src/frontend/index.ts
  src/frontend/screens/index.ts
  tsconfig.json
  yarn.lock
Labels: release: feature

#161 Add documents for sprint 06
  Deliverables/sprint-06/feature-board.png
  Deliverables/sprint-06/feature-board.tsv
  Deliverables/sprint-06/imp-squared-backlog.png
  Deliverables/sprint-06/imp-squared-backlog.tsv
  Deliverables/sprint-06/planning-document.pdf
Labels: sprint-06, release: sprint-deliverables

#163 APP: Build profiles for various devices & Integrating LangChain with a React Native
  eas.json
  metro.config.js
  package.json
  src/frontend/index.ts
  yarn.lock
Labels: release: feature

#164 GitHub CIs: New CI for lint TS code, submit Android and iOS builds to EAS
  .github/issue-branch.yml
  .github/workflows/biomejs.yml
  .github/workflows/check_codestyle.yml
  .github/workflows/checkout_instructions.yml
  .github/workflows/create_link_issue_branch.yml
  .github/workflows/eas_android.yml
  .github/workflows/eas_ios.yml
  .github/workflows/ruff.yml
  .github/workflows/verify_labels.yml
Labels: release: feature

#165 Fix: Limit Biome Js to `./src/frontend` & Ruff to only python files
  .github/workflows/biomejs.yml
  .github/workflows/ruff.yml
Labels: release: bug-fix

#171 154 Created draft for chat screen
  src/bau_stelle/app/_layout.tsx
  src/bau_stelle/app/index.tsx
  src/bau_stelle/components/ChatUI.tsx
Labels: release: feature

#168 App: Navigation, Auth (Login with Google & Email Password), Deeplink, Form Managment, Connection with Firebase
  .env.template
  .gitignore
  app.config.js
  app.json
  babel.config.js
  biome.json
  package.json
  src/frontend/App.tsx
  src/frontend/components/FirebaseProvider/index.tsx
  src/frontend/components/ScreenLayout/index.tsx
  src/frontend/components/SubmitButton/index.tsx
  src/frontend/components/TextInput/index.tsx
  src/frontend/components/UpdateApp/index.tsx
  src/frontend/components/index.ts
  src/frontend/helpers/fonts.ts
  src/frontend/helpers/index.ts
  src/frontend/helpers/screens.ts
  src/frontend/icons/AilixirLogo.tsx
  src/frontend/icons/GoogleIcon.tsx
  src/frontend/icons/index.ts
  src/frontend/routes/AppRoutes.tsx
  src/frontend/routes/AuthRoutes.tsx
  src/frontend/routes/MainRoutes.tsx
  src/frontend/routes/index.ts
  src/frontend/screens/Chat/index.tsx
  src/frontend/screens/Drawer/index.tsx
  src/frontend/screens/Fallback/index.tsx
  src/frontend/screens/ForgotPassword/index.tsx
  src/frontend/screens/ForgotPassword/style.ts
  src/frontend/screens/Landing/LogInWithGoogle.tsx
  src/frontend/screens/Landing/index.tsx
  src/frontend/screens/Landing/style.ts
  src/frontend/screens/Login/index.tsx
  src/frontend/screens/Login/style.ts
  src/frontend/screens/ResetPassword/index.tsx
  src/frontend/screens/ResetPassword/style.ts
  src/frontend/screens/SignUp/index.tsx
  src/frontend/screens/SignUp/style.ts
  src/frontend/screens/index.ts
  tsconfig.json
  yarn.lock
Labels: release: feature

#173 159 add logging functionality
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/__init__.py
  src/backend/log/log.py
Labels: enhancement, release: feature

#170 153 create components for basic visual navigation
  src/frontend/TO INTEGRATE - SideDrawerMenu/app/_layout.tsx
  src/frontend/TO INTEGRATE - SideDrawerMenu/app/index.tsx
  src/frontend/TO INTEGRATE - SideDrawerMenu/components/CustomDrawerContent.tsx
Labels: release: feature

#179 fixed bugs for logging
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/__init__.py
  src/backend/log/log.py
Labels: release: bug-fix

#180 Add documents for sprint 07
  Deliverables/sprint-07/feature-board.png
  Deliverables/sprint-07/feature-board.tsv
  Deliverables/sprint-07/imp-squared-backlog.png
  Deliverables/sprint-07/imp-squared-backlog.tsv
  Deliverables/sprint-07/planning-document.pdf
Labels: sprint-07, release: sprint-deliverables

#183 Fix: Code style (lint and format) for `**/*.py`
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/__init__.py
  src/backend/log/log.py
Labels: release: bug-fix

#184 Documentation for App Setup
  Documentation/WikiPages/ExpoWiki.md
  Documentation/WikiPages/ailixir_project.png
  Documentation/WikiPages/download_build.png
  Documentation/WikiPages/expo_select_organisation.png
  Documentation/WikiPages/using_development_build.png
Labels: release: feature

#185 App: Chat hooks (easy read write chat from any componet context)
  package.json
  src/frontend/components/FirebaseProvider/index.tsx
  src/frontend/helpers/atoms.ts
  src/frontend/helpers/firebase.ts
  src/frontend/helpers/index.ts
  src/frontend/hooks/index.ts
  src/frontend/hooks/useGetAllChat.ts
  src/frontend/hooks/useGetChat.ts
  src/frontend/hooks/useUpdateChat.ts
  src/frontend/types/index.d.ts
  yarn.lock
Labels: release: feature

#187 Database Connection and Chunks
  .env.template
  pdm.lock
  pyproject.toml
  src/backend/Scrapers/AllRecipes/all_recipes.py
  src/backend/Scrapers/Archive/archive.py
  src/backend/Scrapers/BaseScraper/base_scraper.py
  src/backend/Scrapers/Nutritionfacts/nutrition.py
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/Scrapers/PubMed/pub_med.py
  src/backend/Scrapers/YouTube/you_tube.py
  src/backend/Utils/__init__.py
  src/backend/Utils/splitter.py
Labels: release: feature

#194 App: Add New Header Component with Dropdown Menu Integration and Chat switching
  src/frontend/components/ChatItem/index.tsx
  src/frontend/components/DropdownMenu/index.tsx
  src/frontend/components/Header/index.tsx
  src/frontend/components/Header/style.ts
  src/frontend/components/index.ts
  src/frontend/routes/MainRoutes.tsx
  src/frontend/screens/Chat/index.tsx
  src/frontend/screens/Drawer/index.tsx
Labels: release: refactor

#193 Fixed error Podcast
  src/backend/Scrapers/PodCast/pod_cast.py
  src/backend/ScrappingTarget/podcast_target.py
Labels: release: bug-fix

#195 UI custom instructions
  src/frontend/components/TO-INTEGRATE   UI_custom_instructions/app/(tabs)/_layout.tsx
  src/frontend/components/TO-INTEGRATE   UI_custom_instructions/app/(tabs)/index.tsx
  src/frontend/components/TO-INTEGRATE   UI_custom_instructions/components/CustomInstructions.tsx
Labels: release: feature

#206 Add documents for sprint 08
  Deliverables/sprint-08/feature-board.png
  Deliverables/sprint-08/feature-board.tsv
  Deliverables/sprint-08/imp-squared-backlog.png
  Deliverables/sprint-08/imp-squared-backlog.tsv
  Deliverables/sprint-08/planning-document.pdf
Labels: release: sprint-deliverables

#209 Firebase DB Documentation
  Documentation/WikiPages/BuildnRunExpoApp/ExpoWiki.md
  Documentation/WikiPages/BuildnRunExpoApp/ailixir_project.png
  Documentation/WikiPages/BuildnRunExpoApp/download_build.png
  Documentation/WikiPages/BuildnRunExpoApp/expo_select_organisation.png
  Documentation/WikiPages/BuildnRunExpoApp/using_development_build.png
  Documentation/WikiPages/Firestore DB/FirebaseDBWiki.md
  Documentation/WikiPages/Firestore DB/web_authentication_store.png
  Documentation/WikiPages/Firestore DB/web_authentication_window.png
  Documentation/WikiPages/Firestore DB/web_build_tab.png
  Documentation/WikiPages/Firestore DB/web_firestore_chats.png
  Documentation/WikiPages/Firestore DB/web_firestore_users.png
Labels: release: feature

#216 Added prompt engineering and LLM selection option Co-authored-by: Jan Potthof <potthoff.jan@googlemail.com>
  git
Labels: feature, app backend, release: feature

#219 Add documents for sprint 09
  Deliverables/sprint-09/feature-board.png
  Deliverables/sprint-09/feature-board.tsv
  Deliverables/sprint-09/imp-squared-backlog.png
  Deliverables/sprint-09/imp-squared-backlog.tsv
  Deliverables/sprint-09/planning-document.pdf
Labels: sprint-09, release: sprint-deliverables

#217 Added prompt engineering techniques and selection of two LLM models > Co-authored-by : Jan Potthoff<potthoff.jan@googlemail.com>
  src/backend/RAG/LangChain_Implementation/prompt_engineering.py
Labels: feature, app backend, release: feature

#223 Update documents for sprint 09
  Deliverables/sprint-09/feature-board.png
  Deliverables/sprint-09/feature-board.tsv
  Deliverables/sprint-09/planning-document.pdf
Labels: release: sprint-deliverables

#228 Functionality to create new chats
  Documentation/Demo_Videos/sprint10/create_new_chats.m4v
  src/frontend/components/DropdownMenu/index.tsx
  src/frontend/hooks/index.ts
  src/frontend/hooks/useActiveChatId.ts
  src/frontend/hooks/useCreateChat.ts
  src/frontend/hooks/useLLMs.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/DrawerMenu/index.tsx
Labels: release: feature
