Repository amosproj/amos2024ss06-health-ai-framework, pull requests merged in 2024-07, with the labels that each got.

#231 Voice output bugfix + Save chat TXT
  app.json
  package.json
  src/frontend/App.tsx
  src/frontend/components/DropdownMenu/index.tsx
  src/frontend/components/Header/index.tsx
  src/frontend/components/Header/style.ts
  src/frontend/hooks/useActiveChatId.ts
  src/frontend/hooks/useCreateChat.ts
  src/frontend/hooks/useLLMs.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/ChatUI/style.ts
  src/frontend/screens/DrawerMenu/index.tsx
  yarn.lock
Labels: release: refactor

#234 Bugfixes of save txt
  app.json
  package.json
  src/frontend/components/Header/index.tsx
  yarn.lock
Labels: release: bug-fix

#235 Multiple LLM Answers Chat Bubble
  Documentation/Demo_Videos/sprint10/Display_multiple_LLM.mp4
  src/frontend/components/ChatBubble/index.tsx
  src/frontend/components/ChatBubble/style.ts
  src/frontend/components/index.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/ChatUI/style.ts
  src/frontend/types/index.d.ts
Labels: release: feature

#232 Modified the nutrition facts scraper to scrape recipes on the website Nutritionfacts.org
  src/backend/Scrapers/Nutrititonfacts_recipe/__init__.py
  src/backend/Scrapers/Nutrititonfacts_recipe/nutrition_recipes_scraper.py
Labels: app backend, release: sprint-deliverables

#237 Firebase Functions
  .firebaserc
  .gitignore
  firebase.json
  functions/.gitignore
  functions/main.py
  functions/requirements.txt
Labels: release: feature

#236 bugfix-chat-save-after-multiple-LLM
  src/frontend/components/Header/index.tsx
Labels: release: bug-fix

#244 Download Google Docs Content
  .gitignore
  Documentation/Demo_Videos/sprint11/214_download_google_docs.m4v
  functions/main.py
  pdm.lock
  pyproject.toml
  src/backend/RAG/LangChain_Implementation/__init__.py
  src/backend/RAG/LangChain_Implementation/get_google_docs.py
  src/backend/RAG/__init__.py
  src/frontend/screens/ChatUI/index.tsx
Labels: release: feature

#246 (frontend) App Chat Logic for automatic LLM Reponse + Loading Chatbubble
  package.json
  pdm.lock
  pyproject.toml
  src/backend/RAG/FlaskServer/__init__.py
  src/backend/RAG/FlaskServer/server.py
  src/backend/RAG/LangChain_Implementation/get_google_docs.py
  src/backend/RAG/LangChain_Implementation/retriever.py
  src/backend/__init__.py
  src/frontend/components/ChatBubble/index.tsx
  src/frontend/components/Header/index.tsx
  src/frontend/helpers/getLLMResponse.ts
  src/frontend/helpers/index.ts
  src/frontend/hooks/index.ts
  src/frontend/hooks/useCreateChat.ts
  src/frontend/hooks/useUpdateChat.ts
  src/frontend/screens/ChatUI/index.tsx
Labels: release: feature

#248 Integrate custom instructions
  Documentation/Demo_Videos/sprint11/200_Integrate_Context_Input.mp4
  src/frontend/components/PersonalInfoForm/index.tsx
  src/frontend/components/TO-INTEGRATE   UI_custom_instructions/app/(tabs)/_layout.tsx
  src/frontend/components/TO-INTEGRATE   UI_custom_instructions/app/(tabs)/index.tsx
  src/frontend/helpers/screens.ts
  src/frontend/routes/MainRoutes.tsx
  src/frontend/screens/CustomInstructions/index.tsx
  src/frontend/screens/DrawerMenu/index.tsx
  src/frontend/screens/index.ts
Labels: release: feature

#249 Fix lint+format frontend
  package.json
  src/backend/RAG/LangChain_Implementation/get_google_docs.py
  src/frontend/components/ChatBubble/index.tsx
  src/frontend/components/Header/index.tsx
  src/frontend/components/PersonalInfoForm/index.tsx
  src/frontend/components/PersonalInfoForm/style.ts
  src/frontend/hooks/index.ts
  src/frontend/routes/MainRoutes.tsx
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/CustomInstructions/index.tsx
  src/frontend/screens/CustomInstructions/style.ts
  src/frontend/screens/DrawerMenu/index.tsx
  src/frontend/types/index.d.ts
  yarn.lock
Labels: release: refactor

#251 fix: Chat Bubble bug, cycle through LLMs
  src/frontend/components/ChatBubble/index.tsx
Labels: release: bug-fix

#253 Integration of Firebase Functions
  functions/main.py
  package.json
  src/frontend/components/FirebaseProvider/index.tsx
  src/frontend/components/Header/index.tsx
  src/frontend/components/RenderChat/index.tsx
  src/frontend/components/RenderChat/style.ts
  src/frontend/components/index.ts
  src/frontend/hooks/index.ts
  src/frontend/hooks/useGetResponse.tsx
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/types/index.d.ts
  yarn.lock
Labels: release: feature

#258 upload chat logic demo video
  Documentation/Demo_Videos/sprint11/AIResponseChatLogic.m4v
Labels: documentation, sprint-11, release: feature

#259 Add documents for sprint 11
  Deliverables/sprint-11/feature-board.png
  Deliverables/sprint-11/feature-board.tsv
  Deliverables/sprint-11/imp-squared-backlog.tsv
  Deliverables/sprint-11/imp-squred-backlog.png
  Deliverables/sprint-11/planning-document.pdf
Labels: sprint-11, release: sprint-deliverables

#257 History aware Retriever and multiple LLM answers and basic in/out
  src/backend/RAG/LangChain_Implementation/chain.py
Labels: feature, release: feature, release: refactor

#271 fix: ai response being stored in different format and not displayed correctly
  src/frontend/components/RenderChat/index.tsx
  src/frontend/components/RenderChat/style.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/types/index.d.ts
Labels: release: bug-fix

#264 Docs: Firebase functions developer docs
  Documentation/Firebase/functions.md
Labels: release: sprint-deliverables

#270 Firebase functions clean-up
  Documentation/Firebase/functions.md
  functions/.env.template
  functions/chain.py
  functions/config.py
  functions/handlers.py
  functions/main.py
  functions/meta.py
  functions/store.py
Labels: release: feature

#272 Archive combined search terms
  src/backend/Scrapers/Archive/archive.py
Labels: release: bug-fix

#273 Merge Firebase Functions with Original Chat Bubble, ChatUI component Cleanup
  src/frontend/components/ChatBubble/index.tsx
  src/frontend/components/ChatKeyboard/index.tsx
  src/frontend/components/ChatKeyboard/style.ts
  src/frontend/components/RenderChat/index.tsx
  src/frontend/components/VoiceButton/index.tsx
  src/frontend/components/index.ts
  src/frontend/helpers/getLLMResponse.ts
  src/frontend/helpers/index.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/ChatUI/style.ts
Labels: release: feature

#274 Multiple LLM Answer Queries + Voice Output Mutable and Doesn't Read Links
  Documentation/Demo_Videos/sprint12/MultipleLLMQueries_VoiceReadingMutable.m4v
  Documentation/Demo_Videos/sprint12/chatBubbleIntegration.m4v
  src/frontend/components/ChatBubble/index.tsx
  src/frontend/components/ChatBubble/style.ts
  src/frontend/components/DropdownMenu/index.tsx
  src/frontend/components/SpeakButton/index.tsx
  src/frontend/components/SpeakButton/style.ts
  src/frontend/components/index.ts
  src/frontend/hooks/useLLMsTypes.ts
  src/frontend/screens/ChatUI/index.tsx
Labels: release: feature

#278 Small fix for logging in youtube scrapers
  src/backend/Scrapers/YouTube/you_tube.py
Labels: app backend, release: bug-fix

#279 Function chat fix
  functions/handlers.py
  functions/main.py
  functions/requirements.txt
  src/backend/Scrapers/YouTube/you_tube.py
  src/frontend/components/DropdownMenu/index.tsx
  src/frontend/components/RenderChat/index.tsx
  src/frontend/hooks/useUpdateChat.ts
  src/frontend/routes/MainRoutes.tsx
  src/frontend/screens/Chat/index.tsx
  src/frontend/screens/Chat/style.ts
  src/frontend/screens/ChatUI/index.tsx
  src/frontend/screens/DrawerMenu/index.tsx
  src/frontend/screens/index.ts
Labels: release: bug-fix

#281 Add documents for sprint 12
  Deliverables/sprint-12/feature-board.png
  Deliverables/sprint-12/feature-board.tsv
  Deliverables/sprint-12/imp-squared-backlog.png
  Deliverables/sprint-12/imp-squared-backlog.tsv
  Deliverables/sprint-12/planning-document.pdf
Labels: release: sprint-deliverables, sprint-12
